### ISSUE TITLE
 omalloc test failures on musl

### ISSUE THREAD

**Issue by dkwo** [Singular/Singular#1114]
After building singular for Void linux on x86_64 musl, some checks fail:
- on musl 1.2.2: omtTest-m, omtTest-r for omalloc (lots of ***omError_Unknown: unknown error)
[omtTest-r.log](https://github.com/Singular/Singular/files/7115995/omtTest-r.log)
[omtTest-m.log](https://github.com/Singular/Singular/files/7115996/omtTest-m.log)

- on (all) musl: polys_test for libpolys, gives
```
../../build-aux/test-driver: line 109: 24021 Segmentation fault      "$@" > $log_file 2>&1
FAIL: polys_test
```
Logs are here [test-suite.log](https://github.com/Singular/Singular/files/7156922/test-suite.log)

Any hint how to fix these?
Thanks.

**Comment by hannes14** [comment]
- debug version of omalloc tries to read the call graph which probably does not work:
  make sure, that you compile with -DOM_NDEBUG (or set it in omalloc/omConfig.h)
- works with void linux with musl 1.1.24_6
- omalloc requires a working mmap (try --with-malloc=system with configure to use malloc instead of mmap)

**Comment by dkwo** [comment]
Thanks.
I have in omConfig.h
```
/* "Disable debug" */
#ifndef OM_NDEBUG
#define OM_NDEBUG 1
#endif
```
but it fails even with  --with-malloc=system on (self-compiled) newer musl 1.2.2 (on the distro 1.1.24 one it goes fine instead, as you say).

Is there a way to skip these two tests?

**Comment by hannes14** [comment]
- The simple way:remove omtTest-m omtTest-r from TEST=.. in omalloc/Makefile.am
  and try if Singular still works
- Another way: use --disable-omalloc in configure: then memory management is simply using malloc
  instead of the more difficult mmap, valloc, etc. - but you will loose speed in this case.

**Comment by dkwo** [comment]
I'm unable to test first option, as it complains my automake is too old if I edit makefile.
The second option still fails checks, this time it gives many lines of the form

```
make[3]: Entering directory '/builddir/singular-4.2.1/omalloc'
  CC       omtTest_m-omtTestReal.o
In file included from ./../omalloc/omalloc.h:16,
                 from ./../omalloc/omtTestAlloc.c:26,
                 from omtTestReal.c:1:
./../omalloc/xalloc.h:36:27: error: conflicting types for 'omBin'
   36 | typedef size_t            omBin;
      |                           ^~~~~
In file included from ./../omalloc/omtTest.h:23,
                 from ./../omalloc/omtTestAlloc.c:7,
                 from omtTestReal.c:1:
./../omalloc/omStructs.h:12:29: note: previous declaration of 'omBin' was here
   12 | typedef omBin_t*            omBin;
      |                             ^~~~~
In file included from omtTestReal.c:1:
./../omalloc/omtTestAlloc.c: In function 'omtTestAlloc':
./../omalloc/omtTestAlloc.c:36:15: warning: initialization of 'omBin' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
   36 |   omBin bin = NULL;
      |               ^~~~
./../omalloc/omtTestAlloc.c:37:20: warning: initialization of 'omBin' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
   37 |   omBin orig_bin = NULL;
      |                    ^~~~
./../omalloc/omtTestAlloc.c:39:32: error: 'OM_MAX_BLOCK_SIZE' undeclared (first use in this function)
   39 |   if (IS_BIN(spec) && (size <= OM_MAX_BLOCK_SIZE || IS_SPEC_BIN(spec)))
      |
```

**Comment by dkwo** [comment]
Are you able to reproduce omalloc test failure with current version of musl (1.2.2)?

**Comment by hannes14** [comment]
The commit bd8655ab47aaa056e6ffa7d8549d02d87e95298f should fix the make check for '--disable-omalloc'.
And I do not have musl 1.2.2: I used vagrant for voidlinux (which has, after update 1.1.24): how to change to musl1.2.2?

**Comment by dkwo** [comment]
Thanks, the fix seems to work.
Now I'm hitting the failure of polys_test, as it happens for older musl.
(Let me update the first post with its log.)

To get newer musl, could you clone void repo
```
$ git clone git://github.com/void-linux/void-packages.git
$ cd void-packages
$ ./xbps-src binary-bootstrap
```
and then apply this comimt of mine
https://github.com/dkwo/void-packages/commit/f4dd45eabf358ac1b653eba76eb3f8c7adb71266
which updates musl, gets rid of all useless patches, and only adds a patch for large file?
Then `$ ./xbps-src pkg musl` and `xi musl` from within the git branch should allow you to install new musl (xi comes from the package xtools).

Let me know whether that works.

**Comment by dkwo** [comment]
It's possible that some changes in musl malloc function in newer versions trigger this new omalloc test failure in singular.
Perhaps @richfelker can send us in right direction about this?

**Comment by richfelker** [comment]
I need some more context to know what the specific tests failing are, where to find the code for them and for whatever they're testing.

**Comment by dkwo** [comment]
@richfelker Sure. I'm trying to package singular for void linux (https://github.com/void-linux/void-packages/pull/32822), and it fails a couple of checks on musl. The one I wanted to addres first is failure of omalloc tests, which only happens with musl 1.2.2 (not on the 1.1.24 shipped by void).

Specifically, omtTest-m, omtTest-r are failing, with logs in my first message here.
I'm taking the source from `distfiles="https://service.mathematik.uni-kl.de/ftp/pub/Math/Singular/src/${version//./-}/singular-${version}.tar.gz"`
for `version=4.2.1`.

Looking at the makefile here on github,
```
## Test program
TESTS = omtTest-m omtTest-r
check_PROGRAMS = $(TESTS)
# EXTRA_PROGRAMS = omtTest-r
OMTTESTSSOURCES = omtTestReal.c omtTestDebug.c omtTestKeep.c omtTestError.c omtTest.c
```
so the relevant code should be in `omtTestReal.c, omtTestDebug.c, omtTestKeep.c, omtTestError.c, omtTest.c` in Singular/omalloc, which if I understand correctly defines its own version of malloc.

@hannes14 perhaps could add more context

**Comment by hannes14** [comment]
polys_test failed, if rand() returned 0, fixed with https://github.com/Singular/Singular/commit/6e2383111a18b2fa2d3421045625d1d424eb1e25

**Comment by richfelker** [comment]
Is that just part of the failure or the entire issue?

**Comment by hannes14** [comment]
omalloc is a memory manger for small memory blocks (sizeof(void*)... around 1000 bytes),
request for larger blocks are forwarded to malloc.
The omt* files call the many functions of of omalloc (allocation, reallocation, free, each via size or 'bin',
each initialized to 0 or not, ...). If something fails, it should report
"omError.....:<message>". This message is printed via varargs
(fputs( ": ",stderr); vfprintf(stderr, fmt, ap);va_end(ap);
omalloc/omError.c, line 112). It tells the failed test - and seems missing in the log file.

**Comment by hannes14** [comment]
@richfelker: that is the reason (and fix) for the failure of polys_test, but not for the failures of omalloc.

**Comment by dkwo** [comment]
Thanks, that solves the polys issue, and all builds on void linux (using old musl) are now fine.

Let me attach proper log for omalloc (new musl only) test failures.
[test-suite.log](https://github.com/Singular/Singular/files/7197116/test-suite.log)

**Comment by richfelker** [comment]
It looks like something is wrong with the error printing code, and the log is probably not going to be much help until the root cause of that is tracked down and fixed.

**Comment by hannes14** [comment]
The commit https://github.com/Singular/Singular/commit/3a94b411222c9006749e48b383cb1f3d4d1f720c should make "make check"for omalloc more verbose

**Comment by dkwo** [comment]
With that commit, the message becomes like this `***omError_Unknown: unknown error: is_size == 1892 is unaligned`
I attach the new log
[test-suite.log](https://github.com/Singular/Singular/files/7204032/test-suite.log)

**Comment by richfelker** [comment]
OK, I didn't dig all the way down to the allocation, but as far as I can tell either the test is invalid or it's testing something omalloc is intended to satisfy but doesn't, due to a bug in omalloc. `is_size` comes from:

https://github.com/Singular/Singular/blob/3a94b411222c9006749e48b383cb1f3d4d1f720c/omalloc/omtTest.c#L72-L77

where `omSizeOfAddr` comes from:

https://github.com/Singular/Singular/blob/600ab7ba40301e1a41944a1f1e36963e942a129e/omalloc/omAllocSystem.c#L40-L43

Presumably it's expecting `malloc_usable_size` to return some "rounded up to alignment" (what alignment?) size rather than the size that was requested when the memory was allocated. If it wants the size to be aligned, it needs to round up the size when calling `malloc`, not assume `malloc` give it extra memory it didn't request as a bonus.

**Comment by hannes14** [comment]
You are right: the checks assume that the size of a memory block is a multiple of sizeof(long).
It should now only allocate/reallocate/free such blocks.
omalloc (as a library) does not have this requirement.
See https://github.com/Singular/Singular/commit/e1643135645a3cc97af8659018defd2b8617bb4e
This fixes most of the errors from test_suite.log.
Some are of other types: hopefully they are fixed also by this patch.

**Comment by dkwo** [comment]
Thanks a lot, to both of you.
Now I can build singular even with musl 1.2.2 on Void Linux, and it passes checks.
